# Generated by Django 3.1.7 on 2021-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20210316_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certi',
            field=models.ImageField(upload_to=''),
        ),
    ]
