# Generated by Django 3.1.7 on 2021-03-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20210316_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=6),
        ),
    ]
