# Generated by Django 3.1.7 on 2021-03-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20210318_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cnt',
        ),
    ]
